https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [17]:
import torch
import numpy as np

In [5]:
a = torch.tensor([3])
b = torch.tensor([4])
print(a)
print(a+b)


tensor([3])
tensor([7])


In [6]:
print(a.shape)

torch.Size([1])


In [12]:
stacked_tensor = torch.stack([a, b])
print(stacked_tensor.shape)

torch.Size([2, 1])


In [13]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [18]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [19]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7788, 0.8550],
        [0.0350, 0.6094]]) 



In [21]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4214, 0.2632, 0.0783],
        [0.5834, 0.7929, 0.8217]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
